// <auto-generated />
using ContactsServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactsServer.Migrations
{
    [DbContext(typeof(ContactsServerContext))]
    partial class ContactsServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactsServer.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ContactsServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Ronny Andersson",
                            Hash = "MaQmTTsyNkDc5jm35Uy5y/lRYbrRo3tdgnH2/6F25mZ3umaMOAancIVyMCMgHlTcfijIGWxyYXSC7r7KjClNCIV2U0dQ3nDYxKxIhiXvtmyuciU8kODJzyg7msqE9OFCBYzSNrPhzrMl7tKpgV4Y3w7qgSpwHwnydaiKIEr0BrIuCOuqn35KzEcnK8iW89Ne5Ir9whnxFdHQbfIt7yU4+zqREq8M3Nc8CrkGg0KwMPMZ3r0Sm9E5VvRcRNVHqRQIlcPZivMyupK5Li1Uq9lQqIG+3HeGo1vf6oNiKJ+Qe/EzMEU9gPjCguDP6vuucS6GUg/4HM/EmgEoZDkauuL+lA==",
                            Salt = "Iy1rku0NDw+fuprai0A6MWHcS5Xhi7OJDeHu7JptRyHNxHEmfIY+QQ/zV/oqMAFRkvZFVEyyrS9Bn+r1mcGomQ==",
                            UseRole = "Admin",
                            UserName = "roan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
